# -*- coding: utf-8 -*-
"""PCA(Dimensionality_Reduction).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18mJQlCUKVeMCesVnyxmwNFJDa_uRbt6y
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

x,y= make_blobs(n_samples=500,n_features=5,centers=3, cluster_std=1.5,random_state=42)

x

scaler= StandardScaler()
x_scaled= scaler.fit_transform(x)

x_scaled

df= pd.DataFrame(x_scaled,columns=['Features_1','Features_2','Features_3','Features_4','Features_5'])

df

#now we have 5 dimension in this table and we will reduce the dimension by using PCA algorithm..

pca= PCA(n_components=2)  #defining the number of dimension upto which we have reduce..
pca_model= pca.fit_transform(x_scaled) #dimensionality reduction

pca_model

pca_model_df= pd.DataFrame(pca_model,columns=['PCA_1','PCA_2'])  #building data frame of reduced dimension
pca_model_df['label']=y

pca_model_df

sns.scatterplot(data=pca_model_df,x='PCA_1',y='PCA_2',hue='label',palette='Set2' )

#now our principle component analysis is done...